"""Tests for all output renderers."""

from pathlib import Path

import airules.outputs  # noqa: F401
from airules.registry import get_renderer, list_targets


def test_all_targets_registered():
    targets = list_targets()
    expected = {"claude-md", "cursorrules", "copilot", "windsurf", "codex", "aider"}
    assert set(targets.keys()) == expected


def test_claude_md_render(sample_config):
    renderer = get_renderer("claude-md")()
    output = renderer.render(sample_config)

    assert "# myapp" in output
    assert "A test application" in output
    assert "typescript, python" in output
    assert "nextjs, fastapi" in output
    assert "Use functional components" in output
    assert "Prefer const over let" in output
    assert "Use Read tool first" in output  # extra rule from override
    assert "`npm run build`" in output
    assert "API routes in src/app/api/" in output
    assert "Generated by" in output


def test_cursorrules_render(sample_config):
    renderer = get_renderer("cursorrules")()
    output = renderer.render(sample_config)

    assert "You are working on myapp" in output
    assert "Languages: typescript, python" in output
    assert "Use functional components" in output
    assert "`npm run build`" in output


def test_copilot_render(sample_config):
    renderer = get_renderer("copilot")()
    output = renderer.render(sample_config)

    assert "# myapp" in output
    assert "## Tech Stack" in output
    assert "## Code Style" in output
    assert "## Commands" in output


def test_windsurf_render(sample_config):
    renderer = get_renderer("windsurf")()
    output = renderer.render(sample_config)

    assert "Project: myapp" in output
    assert renderer.max_chars == 12_000


def test_codex_render(sample_config):
    renderer = get_renderer("codex")()
    output = renderer.render(sample_config)

    assert "# myapp" in output
    assert renderer.max_chars == 32_768


def test_aider_render(sample_config):
    renderer = get_renderer("aider")()
    output = renderer.render(sample_config)

    assert "# myapp — Conventions" in output
    assert "## Code Style" in output


def test_minimal_config_renders(minimal_config):
    """All renderers should handle minimal config without errors."""
    for target_id, renderer_cls in list_targets().items():
        renderer = renderer_cls()
        output = renderer.render(minimal_config)
        assert isinstance(output, str)
        assert len(output) > 0


def test_write_creates_file(sample_config, tmp_path):
    renderer = get_renderer("claude-md")()
    output_path = renderer.write(sample_config, tmp_path)

    assert output_path.exists()
    content = output_path.read_text()
    assert "# myapp" in content


def test_write_creates_subdirectory(sample_config, tmp_path):
    """Copilot output creates .github/ directory."""
    renderer = get_renderer("copilot")()
    output_path = renderer.write(sample_config, tmp_path)

    assert output_path.exists()
    assert ".github" in str(output_path)


def test_windsurf_truncation(sample_config):
    """Windsurf renderer should respect char limit."""
    # Add a ton of rules to exceed limit
    sample_config.style.rules = [f"Rule number {i}" for i in range(1000)]
    renderer = get_renderer("windsurf")()
    output = renderer.render(sample_config)

    # Write should truncate
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        path = renderer.write(sample_config, Path(tmp))
        content = path.read_text()
        assert len(content) <= 12_000
